server:
  port: 0

spring:
  application:
    name: kafka-message-service

  mail:
    host: localhost
    port: 1025

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: message-service
      auto-offset-reset: earliest

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8280/realms/task-manager-microservices
            user-name-attribute: preferred_username
        registration:
          keycloak:
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            client-id: kafka-message-service
            client-secret: 5PWMhEBYdXinYreRb8MZEZj7yNTxdGe7
            scope:
              - openid
              - microprofile-jwt
              - metrics
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8280/realms/task-manager-microservices/protocol/openid-connect/certs

eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka

kafka:
  forgot-password-topic: forgot-password
  bootstrap-server: localhost:9092

jwt:
  secretKey: ccb63ce7180e6ebc737ac6da9570fe55b785d924b074261b5a542e38cfb4a54d
  expires: 24h

common:
  baseUrl: http://localhost:8080/

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.vote.AffirmativeBased: DEBUG
    org.springframework.security.access.vote.AuthenticatedVoter: DEBUG