version: '3.8'

x-defaults: &default-backend-configuration
  networks:
    - backend
  restart: unless-stopped

services:
  user-keycloak-db:
    <<: *default-backend-configuration
    container_name: user-keycloak-db
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-db
    ports:
      - "5411:5432"
    volumes:
      - user-task-manager-db:/var/lib/postgresql/data

  keycloak-task-manager:
    <<: *default-backend-configuration
    container_name: task-manager-keycloak
    image: quay.io/keycloak/keycloak:24.0.2
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3" ]
      interval: 5s
      timeout: 7s
      retries: 5
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://user-keycloak-db/user-db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    depends_on:
      - user-keycloak-db
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/

networks:
  backend:
    driver: bridge

volumes:
  user-task-manager-db:
