FROM quay.io/keycloak/keycloak:24.0.2
COPY config/keycloak/realm-export.json /opt/keycloak/data/import/realm-export.json
COPY config/keycloak/themes/reset-password-web.ftl /opt/keycloak/themes/mytheme/email/html/executeActions.ftl
COPY config/keycloak/themes/reset-password-txt.ftl /opt/keycloak/themes/mytheme/email/text/executeActions.ftl
COPY ./custom-user-provider-mongodb/target/keycloak-mongodb-user-storage-provider.jar /opt/keycloak/providers/keycloak-mongodb-user-storage-provider.jar
COPY ./custom-event-listener/target/custom-user-session-listener.jar /opt/keycloak/providers/custom-user-session-listener.jar
