version: '3.8'

services:
  mongodb-keycloak:
    container_name: mongodb-keycloak
    image: mongo:latest
    environment:
      MONGODB_INIT_DB: user-db
    volumes:
      - mongodb-keycloak-provider:/data/db
    ports:
      - "27022:27017"

  keycloak-provider:
    container_name: keycloak-provider
    image: quay.io/keycloak/keycloak:24.0.4
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3" ]
      interval: 5s
      timeout: 7s
      retries: 5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8079:8080"
    command: [ "start-dev", "--verbose" ]
    volumes:
      - ./target/keycloak-mongodb-user-storage-provider.jar:/opt/keycloak/providers/keycloak-mongodb-user-storage-provider.jar


volumes:
  mongodb-keycloak-provider: