apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-service
spec:
  selector:
    matchLabels:
      app: eureka-discovery-service
  template:
    metadata:
      labels:
        app: eureka-discovery-service
    spec:
      containers:
        - name: eureka-discovery-service
          image: fyuizee/eureka-discovery-service
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: eureka-discovery-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-service
spec:
  selector:
    app: eureka-discovery-service
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-discovery-service-config
data:
  SPRING_PROFILES_ACTIVE: k8s