apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-message-service
  template:
    metadata:
      labels:
        app: kafka-message-service
    spec:
      containers:
        - name: kafka-message-service
          image: fyuizee/kafka-message-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: kafka-message-service-config
                  key: SPRING_PROFILES_ACTIVE
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-message-service-config
data:
  SPRING_PROFILES_ACTIVE: k8s