server:
  port: 8888

spring:
  application:
    name: config-cloud-service

  cloud:
    config:
     server:
       git:
         uri: https://github.com/broxzx/TaskManager-Microservices
         searchPaths: config
         default-label: main