server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service

  config:
    import: "optional:configserver:http://localhost:8888"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/task-manager-microservices/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: eureka-discovery-server
            client-secret: yE95fpOusvXrQyXjfsPWagqHy0YgfMy3
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/task-manager-microservices
            user-name-attribute: preferred_username

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always