apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-loki
  template:
    metadata:
      labels:
        app: grafana-loki
    spec:
      containers:
        - name: grafana-loki
          image: grafana/loki:2.9.4
          ports:
            - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loki
spec:
  selector:
    app: grafana-loki
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP