apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-dev
  template:
    metadata:
      labels:
        app: mail-dev
    spec:
      containers:
        - name: mail-dev
          image: maildev/maildev
          ports:
            - containerPort: 1080
            - containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: mail-dev
spec:
  selector:
    app: mail-dev
  type: ClusterIP
  ports:
    - port: 1080
      targetPort: 1080
      protocol: TCP
      name: outer
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: inner