apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-user
  template:
    metadata:
      labels:
        app: mongodb-user
    spec:
      containers:
        - name: mongo-user-db
          image: mongo:7.0-jammy
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: user-db
          volumeMounts:
            - mountPath: /data/user-db
              name: mongo-user-data
          resources: { }
      volumes:
        - name: mongo-user-data
          persistentVolumeClaim:
            claimName: mongo-user-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user-service
spec:
  type: NodePort
  selector:
    app: mongodb-user
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-user-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/user-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-user-pvc
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi