apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-task-db
spec:
  selector:
    matchLabels:
      app: mongo-task-db
  template:
    metadata:
      labels:
        app: mongo-task-db
    spec:
      containers:
        - name: mongo-task-db
          image: mongo:7.0-jammy
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: mongo-task-db-config
          volumeMounts:
            - mountPath: /data/db
              name: task-db-mount
      volumes:
        - name: task-db-mount
          persistentVolumeClaim:
            claimName: mongo-task-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-task-db
spec:
  selector:
    app: mongo-task-db
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-task-db-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/task-db
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-task-db-pvc
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-task-db-config
data:
  MONGO_INITDB_DATABASE: "tasks-db"