server:
  port: 8084

spring:
  application:
    name: task-service

  data:
    mongodb:
      uri: mongodb://mongo-task-db:27017/tasks-db

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/task-manager-microservices
        registration:
          keycloak:
            client-id: task-service
            client-secret: pvI9oSFYeKKKNml9fkUt57dS4R3hECwj
            scope:
              - openid
              - microprofile-jwt
              - metrics
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/task-manager-microservices/protocol/openid-connect/certs

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://grafana-tempo:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      probes:
        enabled: true
      validate-group-membership: true
      group:
        readiness:
          show-details: always
          show-components: always
        liveness:
          show-details: always
          show-components: always

keycloak:
  realm: task-manager-microservices
  client-id: task-service
  client-secret: pvI9oSFYeKKKNml9fkUt57dS4R3hECwj
  server-url: http://keycloak:8080
  scope: view_users

url:
  user-service: http://user-service:8082
  project-service: http://project-service:8083

logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.vote.AffirmativeBased: DEBUG
    org.springframework.security.access.vote.AuthenticatedVoter: DEBUG
  config: classpath:logback-dev.xml