server:
  port: 8084

spring:
  application:
    name: task-service

  data:
    mongodb:
      uri: mongodb://localhost:27001/tasks-db

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8280/realms/task-manager-microservices
        registration:
          keycloak:
            client-id: task-service
            client-secret: pvI9oSFYeKKKNml9fkUt57dS4R3hECwj
            scope:
              - openid
              - microprofile-jwt
              - metrics
            authorization-grant-type: client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8280/realms/task-manager-microservices/protocol/openid-connect/certs

management:
  server:
    port: 9104
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

keycloak:
  realm: task-manager-microservices
  client-id: task-service
  client-secret: pvI9oSFYeKKKNml9fkUt57dS4R3hECwj
  server-url: http://localhost:8280
  scope: view_users

url:
  user-service: http://user-service:8082
  project-service: http://project-service:8083

logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.vote.AffirmativeBased: DEBUG
    org.springframework.security.access.vote.AuthenticatedVoter: DEBUG
  config: classpath:logback.xml