server:
  port: 0

spring:
  application:
    name: project-service

  data:
    mongodb:
      host: localhost
      port: 27015
      database: projects-db

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8280/realms/task-manager-microservices
            user-name-attribute: preferred_username

        registration:
          keycloak:
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            client-id: project-service
            client-secret: SKW61GhBo1qz6whNaeJzMaUVpRZerI5J
            authorization-grant-type: client_credentials
            scope:
              - openid
              - microprofile-jwt
              - metrics
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8280/realms/task-manager-microservices/protocol/openid-connect/certs

eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  realm: task-manager-microservices
  client-id: project-service
  client-secret: SKW61GhBo1qz6whNaeJzMaUVpRZerI5J
  server-url: http://localhost:8280

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    org.springframework.security.access.vote.AffirmativeBased: DEBUG
    org.springframework.security.access.vote.AuthenticatedVoter: DEBUG